/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class javatraining_module2_NativeTest */

#ifndef _Included_javatraining_module2_NativeTest
#define _Included_javatraining_module2_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     javatraining_module2_NativeTest
 * Method:    callNative
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_javatraining_module2_NativeTest_callNative(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
